### ISSUE TITLE
Accuracy Difference between Face Recognition and Face Verification

### ISSUE THREAD

**Issue by gopi1989** [cmusatyalab/openface#63] opened 2015-11-30 15:57 UTC
Hi bamos,

I tested the demo/web today.I experience that face verification is low in accuracy when compared to face recognition.Please see my Test cases,Do i am right in my thought? If there is any difference please explain why it's happening?.

My test cases:
1. Trained 150 images for single person (with label "Person 1" )and tested it for Face verification
It detect the untrained person as "Person 1".
2. Trained 30 Images for two person (with label "Person 1,Person 2") and tested it for Face Recognition.
It classify precisely and detect the two person exactly.

Thanks with Regards ,
Gopi.

**Comment by bamos** [comment] 2015-11-30 16:19
Hi @gopi1989 - thanks for the messages.
I'm closing this as a duplicate of your mailing list post:
https://groups.google.com/forum/#!topic/cmu-openface/IpiW4tgU4RA

-Brandon.

**Closed by bamos** 2015-11-30 16:19 UTC
