### ISSUE TITLE
issue with crossmapnormalization layer

### ISSUE THREAD

**Issue by AkankshaJ** [cmusatyalab/openface#102] opened 2016-03-04 03:41 UTC
Hi Brandon,

**If i dont use fbnn, i get the following error**

Error getting result from Torch subprocess.

Line read:

Exception:

could not convert string to float:

stdout:

stderr: /home/akanksha/torch/install/bin/luajit: /home/akanksha/torch/install/share/lua/5.1/torch/File.lua:334: unknown Torch class 
stack traceback:
[C]: in function 'error'
/home/akanksha/torch/install/share/lua/5.1/torch/File.lua:334: in function 'readObject'
/home/akanksha/torch/install/share/lua/5.1/torch/File.lua:360: in function 'readObject'
/home/akanksha/torch/install/share/lua/5.1/torch/File.lua:360: in function 'readObject'
/home/akanksha/torch/install/share/lua/5.1/nn/Module.lua:154: in function 'read'
/home/akanksha/torch/install/share/lua/5.1/torch/File.lua:342: in function 'readObject'
/home/akanksha/torch/install/share/lua/5.1/torch/File.lua:391: in function 'load'
...torch/demos/openface-master/openface/openface_server.lua:46: in main chunk
[C]: in function 'dofile'
...ksha/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
[C]: at 0x00406670

**Should i rectify it at the training level?? Since it seems that it uses fbnn crossmapnormaliztion during training ?**

**Comment by bamos** [comment] 2016-03-04 12:46
Duplicate of #101

**Closed by bamos** 2016-03-04 12:46 UTC
