### ISSUE TITLE
Use caffe instead of Torch

### ISSUE THREAD

**Issue by MrSaman** [cmusatyalab/openface#94] opened 2016-02-12 10:09 UTC
Hi

Is it prefer to use caffe framework instead of torch ?

**Comment by bamos** [comment] 2016-02-12 12:42
Please see https://github.com/cmusatyalab/openface/blob/master/CONTRIBUTING.md.

This is also a duplicate of #1.

**Closed by bamos** 2016-02-12 12:42 UTC
