### ISSUE TITLE
"forward" function hangs after being called 22 times

### ISSUE THREAD

**Issue by nixingyang** [cmusatyalab/openface#87] opened 2016-01-27 20:18 UTC
Hi,
First of all, I'd like to thank the developers for this interesting project.
Let's check the code below:
```Python
for index in range(100):
    print("Working on {:d} ...".format(index))
    feature = net.forward(facial_image_in_RGB)
```
**facial_image_in_RGB** is a numpy array which contains the facial image. The code always hangs at the **forward** function when index is 22. Can someone confirm this issue? Any help would be greatly appreciated. The version that I use is **OpenFace 0.2.0**.

**Comment by bamos** [comment] 2016-01-27 21:10
Hi @nixingyang - I haven't seen this issue before and I'm not able to reproduce this. I just ran a loop like the one you posted that just obtains the representations and it successfully ran 100 iterations.
Can you find where it's hanging by adding print statements to the OpenFace code?

My guess is that it's the readline call into the Torch subprocess at
https://github.com/cmusatyalab/openface/blob/0.2.0/openface/torch_neural_net.py#L105

-Brandon.

**Comment by nixingyang** [comment] 2016-01-27 21:49
@bamos Hi, thanks for the prompt reply. Your guess is correct and I can confirm that the program hangs at that line. Is there quick fix for this issue? Currently, I am using other tricks to rerun to program again and again. I won't be bothered by this issue once I retrieve the features from all the images.

**Comment by bamos** [comment] 2016-01-27 22:17
I'm not sure how to fix this yet. To further find out where it's coming from, can you
find what place in [openface_server.lua](https://github.com/cmusatyalab/openface/blob/master/openface/openface_server.lua)
is getting to? Don't write to stdout, but write some info into a file.

Are you batch processing a set of images? If so you can use `util/align-dlib.py` and then `batch-represent` as described in http://cmusatyalab.github.io/openface/training-new-models/.

**Comment by nixingyang** [comment] 2016-01-28 09:00
@bamos Sorry, I am not familiar with Lua script. This issue might be related to my installation. I use Arch and those bleeding edge packages could introduce weird bugs. We may omit this issue for now until someone else also encounters the same problem.

**Comment by bamos** [comment] 2016-01-28 14:29
File IO in Lua works as expected: http://www.tutorialspoint.com/lua/lua_file_io.htm.

Interesting, I also have OpenFace working on Arch (but primarily develop on Ubuntu) and am unable to reproduce this issue on it. I wonder if it would still hang on your machine if you use our Docker image?

**Comment by nixingyang** [comment] 2016-01-28 20:24
@bamos Thanks for the link. I have tried to debug **openface_server.lua**. The new code looks like this:
```Lua
write_to_log("4")
if opt.cuda then
   write_to_log("5")
   imgCuda:copy(img)
   rep = net:forward(imgCuda):float()
else
   write_to_log("6")
   rep = net:forward(img)
end
write_to_log("7")
```
At the 23th iteration, the code hangs after "6" is written to the log.
By the way, how can I set the OpenFace to use the GPU? It seems that my environment is still using the CPU. I can use the Theano and Caffe in GPU mode without problem.

**Comment by bamos** [comment] 2016-01-28 20:48
Interesting! This is unexpectedly hanging in a call to the neural network. Can you try running [util/profile-network.lua](https://github.com/cmusatyalab/openface/blob/master/util/profile-network.lua), which just sends random values through the network in a loop? From what we've found out, I expect your system to hang on a forward pass in here too. You can add print statements here instead of writing to a file to see.

Also, you can pass `cuda=True` to [openface.TorchNeuralNetwork](http://openface-api.readthedocs.org/en/latest/openface.html#openface-torchneuralnet-class) to use CUDA.

**Comment by nixingyang** [comment] 2016-01-28 21:33
@bamos I simply execute **"th util/profile-network.lua"** and a lot of warnings pop up. It reads: 
```
OpenBLAS Warning : Detect OpenMP Loop and this application may hang. Please rebuild the library with USE_OPENMP=1 option.
```
After setting OpenFace to use GPU, the computation speed is much faster and this hanging issue is also solved. It happens only in CPU mode.

**Comment by bamos** [comment] 2016-01-28 21:40
Very strange! I'm glad we found that message, but it's still confusing since it's not clear if the error is from OpenBLAS or Torch and what needs to be recompiled with the OpenMP flag. As far as I'm aware the Torch installation process should have built with the correct flags. I'm closing this issue since GPU mode is working well for you and any changes to resolve this need to be added to Torch (or OpenBLAS?).

-Brandon.

**Closed by bamos** 2016-01-28 21:40 UTC

**Comment by nixingyang** [comment] 2016-01-28 21:53
Thank you for all your assistance. :+1:

**Comment by bamos** [comment] 2016-01-29 15:38
Hi @nixingyang - if you get a chance, can you try pulling the latest code from the master and re-running your example that hangs? I just removed stderr piping from the Torch subprocess and I think these should pass through the warnings you're getting so they are clearer for people in the future.

-Brandon.

**Comment by nixingyang** [comment] 2016-01-30 18:31
@bamos I re-installed the latest code. The program does not hang in CPU mode. However, the **OpenBLAS Warning** still pops up.

**Comment by shamangary** [comment] 2016-08-25 07:40
I have solved the OpenBLAS warning by a single line. (But I am not sure if it is OK or not. Plz check)

#How to fix the warning?
-- Add this line to the function "repBatch()" inside "./batch-represent/batch-represent.lua"
torch.setnumthreads(1)
