### ISSUE TITLE
Web demo issue 

### ISSUE THREAD

**Issue by trungdn** [cmusatyalab/openface#95] opened 2016-02-15 14:47 UTC
Hi Brandon,

I'm trying to run web demo on cloud9. I set up by manual. Everything looks good except when I run the web, I add person then click training, then nothing happened nothing training. Looks like web server log got nothing. 

2016-02-15 14:25:26+0000 [-] Log opened.
2016-02-15 14:25:26+0000 [-] WebSocketServerFactory starting on 9000
2016-02-15 14:25:26+0000 [-] Starting factory <autobahn.twisted.websocket.WebSocketServerFactory object at 0x7f65810891d0>
2016-02-15 14:37:49+0000 [-] Received SIGTERM, shutting down.
2016-02-15 14:37:49+0000 [autobahn.twisted.websocket.WebSocketServerFactory] (TCP Port 9000 Closed)
2016-02-15 14:37:49+0000 [autobahn.twisted.websocket.WebSocketServerFactory] Stopping factory <autobahn.twisted.websocket.WebSocketServerFactory object at 0x7f65810891d0>
2016-02-15 14:37:49+0000 [-] Main loop terminated.

Thank you.

**Comment by bamos** [comment] 2016-02-15 20:07
Hi, thanks for filing an issue with us. However, I am closing this issue because it is a duplicate of [your mailing list post](https://groups.google.com/forum/#!topic/cmu-openface/bQ2PKVAk9f8). Please review our [contribution guidelines](https://github.com/cmusatyalab/openface/blob/master/CONTRIBUTING.md).

-Brandon.

**Closed by bamos** 2016-02-15 20:07 UTC
