### ISSUE TITLE
new Classification Model

### ISSUE THREAD

**Issue by haridatascientist** [cmusatyalab/openface#236] opened 2017-02-13 07:37 UTC
### Context of the issue.
Train with 1-million MS celebrity dataset

### Expected behavior
i want the new DNN model which gives greater accuracy

### Actual behavior.
i trained my dataset with nn4.small2v11, i have the results also.

### Steps to reproduce.
1.as you mentioned in the former post that you have trained the 1milion MS celeb datset classifier DNN model file and soon you will release it. 
2.i am expecting the classifier DNN models trained with 1.1million MS celeb dataset,  2.VGG dataset. and also  which  one gives better results for LFW.

### OS and hardware information.

+ Operating system: [ubuntu 14.04]
+ Torch version: [todo]
+ CPU architecture: [todo]
+ GPU type (if using): [nividia gt 640]

**Comment by jaharkes** [comment] 2017-02-13 17:13
This seems to be a duplicate of #170  and #103, possibly indirectly also #119.

Either way I am not aware of anyone actually finishing training a new model based on the MS-Celeb-1M, VGG, or washed up CASIA webface datasets. Any progress on this should be covered by the open issues I linked.

**Closed by jaharkes** 2017-02-13 17:13 UTC
